version: '3.8'
services:
  db:
    container_name: coursesystem
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=coursesystem
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: course-system-redis
    image: bitnami/redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=coursesystem
    ports:
      - '6379:6379'
    volumes:
      - ../../docker-volumes/course-erp-redis:/bitnami/redis/data
volumes:
  postgres_data: